---
- name: Configure Cisco Hostname and DNS
  hosts: cisco
  
  vars:
    hostname: "YeslabSW01"
    dns: "114.114.114.114 8.8.8.8"
    loopback_ip: "100.100.100.100"

  tasks: 
    - name: configure hostname
      cisco.ios.ios_config:
        lines: 
          - hostname {{ hostname }}
    - name: configure DNS
      cisco.ios.ios_config:
        lines: 
          - ip name-server {{ dns }}

    - name: configure loopback interface
      cisco.ios.ios_config:
        lines:
          - ip address {{ loopback_ip }} 255.255.255.0
          - description Configured-with-ansible
        parents: interface Loopback0
