---
- name: Configure ACL
  hosts: cisco
  gather_facts: no

  vars_files:
     - Config_MyACL.yaml
    
  tasks:
    - name: configure acl
      cisco.ios.ios_config:
        lines:
          - deny {{ item.ip }}
        parents:
          - ip access-list standard {{ item.num }}
      with_items: "{{ acl_list }}"
